name: Update AoC Badges
# See https://github.com/marketplace/actions/aoc-badges
on:
  schedule: # run workflow based on schedule
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

  workflow_dispatch: # allow to manually start the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1732418 # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2021
      - uses: stefanzweifel/git-auto-commit-action@v4 # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md