name: Update README ⭐
on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1732418
          leaderboardId: 1732418
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars